name: Windows Build

on:
  push:
    branches:
      - main
  pull_request: 

env:
  BOOST_VERSION: "1.85.0"
  vcpkg_ref: "cd5e746ec203c8c3c61647e0886a8df8c1e78e41"
  BOOST_ROOT: "$GITHUB_WORKSPACE/3rdparty/boost"
  BOOST_URL: "https://sourceforge.net/projects/boost/files/boost/1.85.0/boost_1_85_0.tar.bz2/download"
  QT_ROOT: "$GITHUB_WORKSPACE/3rdparty/qt"
  QT_URL: "https://github.com/shun-iwasawa/qt5/releases/download/v5.15.2_wintab/Qt5.15.2_wintab.zip"
  LTIFF: "$GITHUB_WORKSPACE/thirdparty/tiff-4.0.3/lib/LibTIFF-4.0.3_2015_64.lib"

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v4

    - name: Checkout Dependencies
      run: |
        git clone https://github.com/mypaint/libmypaint libmypaint --branch 70f7686db792fa4953dc60f28a322bf2cd388ed7 --depth 1
        git clone https://github.com/xiaoyeli/superlu superlu --branch a3d5233770f0caad4bc4578b46d3b26af99e9c19 --depth 1

    - name: Install vcpkg
      run: |
        rm -r -fo C:/vcpkg
        git clone https://github.com/Microsoft/vcpkg C:/vcpkg
        cd C:/vcpkg
        git checkout ${{ env.vcpkg_ref }}
        ./bootstrap-vcpkg.bat

    - uses: actions/cache@v4
      with:
        path: C:/vcpkg/installed
        key: ${{ runner.os }}-vcpkg-${{ env.vcpkg_ref }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}-vcpkg-${{ env.vcpkg_ref }}-

    - name: Install Libraries with vcpkg
      run: |
        vcpkg install --clean-after-build --triplet x64-windows icu
        vcpkg install --clean-after-build --triplet x64-windows-static json-c libjpeg-turbo libpng lz4 lzo openblas zlib
        vcpkg install --clean-after-build --triplet x64-windows freeglut glew
        vcpkg install --clean-after-build --triplet x64-windows --recurse opencv[world]
        ls -Recurse C:/vcpkg/installed -Filter *.pdb | rm

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v4
      with:
        path: ${{ env.QT_ROOT }}
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: |
        QT_ROOT=$(echo $QT_ROOT | sed 's/\\/\//g')
        mkdir -p $QT_ROOT
        curl --progress-bar -L -o $QT_ROOT/Qt.zip $QT_URL
        7z -o$QT_ROOT x $QT_ROOT/Qt.zip -y -bd
        rm -f $QT_ROOT/Qt.zip
      shell: bash

    - name: Cache Boost
      id: cache-boost
      uses: actions/cache@v4
      with:
        path: ${{ env.BOOST_ROOT }}
        key: boost-${{ env.BOOST_VERSION }}

    - name: Install Boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        BOOST_ROOT=$(echo $BOOST_ROOT | sed 's/\\/\//g')
        mkdir -p $env.BOOST_ROOT
        curl --progress-bar --location --output $BOOST_ROOT/download.tar.bz2 $BOOST_URL
        7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar.bz2 -y -bd
        7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar -y -bd
        cd $BOOST_ROOT && cp -r boost_*/* .
        rm -rf boost_*/* download.tar.bz2 download.tar
      shell: bash

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.1'

    - name: Build libtiff
      run: |
        cd thirdparty/tiff-4.0.3
        cp libtiff/tif_config.vc.h libtiff/tif_config.h
        cp libtiff/tiffconf.vc.h libtiff/tiffconf.h
        cd prj/LibTIFF
        $env:Path += ';C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin'
        msbuild LibTIFF.vcxproj /p:PlatformToolset=v142 /p:Platform=x64 /p:Configuration=Release -maxcpucount:3

    - name: Build libmypaint
      run: |
        cd libmypaint
        cp ../.github/workflows/CMakeLists.txt .
        echo '#define MYPAINT_CONFIG_USE_GLIB 0' > config.h
        python generate.py mypaint-brush-settings-gen.h brushsettings-gen.h
        mkdir build
        cd build
        cmake ../ -G 'Visual Studio 16 2019' -Ax64 -Djson-c_DIR='C:/vcpkg/installed/x64-windows-static/share/json-c/' -DJSON-C_INCLUDE_DIR='C:/vcpkg/installed/x64-windows-static/include/json-c/'
        cmake --build . --config Release
        cp C:/vcpkg/installed/x64-windows-static/lib/json-c.lib .
        $env:Path += ';C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64'
        lib /OUT:libmypaint.lib Release/libmypaint.lib json-c.lib
        cp libmypaint.lib Release/libmypaint.lib

    - name: Build superlu
      run: |
        cd superlu
        mkdir build
        cd build
        cmake ../ -G 'Visual Studio 16 2019' -Ax64 -DXSDK_ENABLE_Fortran=OFF -Denable_tests=OFF
        cmake --build . --config Release

    - name: Workaround for Library Paths
      run: |
        cd thirdparty
        cp C:/vcpkg/installed/x64-windows-static/lib/libpng16.lib libpng-1.6.21/lib/libpng16_2015_64.lib
        cp C:/vcpkg/installed/x64-windows-static/lib/lz4.lib Lz4/Lz4_131/lz4_64.lib
        cp C:/vcpkg/installed/x64-windows-static/lib/lzo2.lib lzo/2.03/LZO_lib/lzo2_64.lib
        cp C:/vcpkg/installed/x64-windows-static/lib/openblas.lib openblas/libopenblas_64.lib
        cp C:/vcpkg/installed/x64-windows-static/lib/zlib.lib zlib-1.2.8/lib/zlib-1.2.8_2015_64.lib
        cp C:/vcpkg/installed/x64-windows/lib/freeglut.lib glut/3.7.6/lib/glut64.lib
        cp C:/vcpkg/installed/x64-windows/lib/glew32.lib glew/glew-1.9.0/lib/glew64.lib
        cp D:/a/opentoonz/opentoonz/libmypaint/build/Release/libmypaint.lib libmypaint/dist/64/libmypaint.lib
        cp D:/a/opentoonz/opentoonz/superlu/build/SRC/Release/superlu.lib superlu/SuperLU_2015_64.lib
        cp D:/a/opentoonz/opentoonz/thirdparty/tiff-4.0.3/prj/LibTIFF/x64/Release/LibTIFF.lib tiff-4.0.3/lib/LibTIFF-4.0.3_2015_64.lib
        cp C:/vcpkg/installed/x64-windows-static/lib/turbojpeg.lib libjpeg-turbo/lib/turbojpeg-static_2015_64.lib
        cp C:/vcpkg/installed/x64-windows-static/lib/jpeg.lib libjpeg-turbo/lib/jpeg-static_2015_64.lib

    - name: Copy Headers
      run: |
        cd thirdparty
        cp libpng-1.6.21/scripts/pnglibconf.h.prebuilt libpng-1.6.21/pnglibconf.h

    - name: Build Main Project
      run: |
        cd toonz
        mkdir build
        cd build
        cmake .. -G 'Visual Studio 16 2019' -Ax64 -DQT_PATH="$env:QT_ROOT" -DBOOST_ROOT="$env:BOOST_ROOT"
        cmake --build . --config RelWithDebInfo --target ALL_BUILD

    - name: Package Build Artifacts
      run: |
        cd toonz/build
        cp RelWithDebInfo/OpenToonz.exe ../../../
        7z a -tzip -mx=9 artifacts.zip RelWithDebInfo/
      shell: bash
      env:
        BOOST_ROOT: ${{ env.BOOST_ROOT }}
        QT_ROOT: ${{ env.QT_ROOT }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: toonz-build
        path: toonz/build/artifacts.zip
